from .user_routes import user_bp
from .role_routes import role_bp
from .auth_routes import auth_bp
from .symptom_routes import symptom_bp
from .disease_routes import disease_bp
from .admin_route.admin_route import admin_bp
from .expert_route.expert_route import expert_bp
from .rule_condition_route import rule_condition_bp
from .prevention_route import prevention_bp
from .treatment_route import treatment_bp
from .audit_routes import audit_bp
from .rule_routes import rule_bp